export interface IEmployee {
     Id : number;
     EmpCode: string;
     EmpCard: string;
     Title: string;
     NameThai: string;
     NameEng: string;
     NickName: string;
     Age : number;
     Sex: string;
     BeginDate : Date;
     ResidentDate : Date;
     EmptypeCode: string;
     DeptCode: string;
     DivisionCode: string;
     SectionCode: string;
     GroupCode: string;
     GroupMis: string;
     PositionCode: string;
     LevelCode: string;
     AreaId: string;
     LocateId: string;
     EduLevel: string;
     EduInstitute: string;
     EduBranch: string;
     EduCertificate: string;
     EmpStatusOut : boolean;
     OutDate : Date;
     Jdno: string;
     GroupId: string;
     LevelId: string;
     WorkId: string;
     DepartmentString: string;
     SectionString: string;
     DivisionString: string;
     GroupString: string;
     EmployeeTypeString: string;
     LocationString: string;
     EmployeePicture: string;
}